spring:
  application:
    name: ms-hoxton

  sleuth:
    enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: https://zipkin-dev.hcuge.ch
    sender:
      type: WEB
  cloud:
    bus:
      enabled: false
      refresh:
        enabled: false
      trace:
        enabled: false
eureka:
  client:
    enabled: false          
